<a href="https://colab.research.google.com/github/Maziger/Laksegate-master-thesis/blob/main/POC/FINSPID_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# FINSPID (Financial News and Stock Price Integration Dataset)

github: https://github.com/Zdong104/FNSPID_Financial_News_Dataset

Hugging face: https://huggingface.co/papers/2402.06698

Paper: https://arxiv.org/pdf/2402.06698

In [ ]:
!git clone https://github.com/Zdong104/FNSPID_Financial_News_Dataset.git

Cloning into 'FNSPID_Financial_News_Dataset'...
remote: Enumerating objects: 1511, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 1511 (delta 162), reused 120 (delta 120), pack-reused 1314 (from 1)
Receiving objects: 100% (1511/1511), 105.90 MiB | 20.74 MiB/s, done.
Resolving deltas: 100% (465/465), done.
Updating files: 100% (1083/1083), done.

In [ ]:
%cd FNSPID_Financial_News_Dataset
!pip install -r requirements.txt

/content/FNSPID_Financial_News_Dataset
Collecting numpy~=1.26.0 (from -r requirements.txt (line 1))
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.9 MB/s eta 0:00:00
Collecting selenium~=4.16.0 (from -r requirements.txt (line 2))
  Downloading selenium-4.16.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pandas~=2.0.3 (from -r requirements.txt (line 3))
  Downloading pandas-2.0.3.tar.gz (5.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 69.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [ ]:
from google.colab import userdata
HF_TOKEN = userdata.get('HF_TOKEN')

In [ ]:
# Download takes ~5 minutes, so maybe get a cup of coffee or do some push-ups
from datasets import load_dataset

dataset = load_dataset('Zihan1004/FNSPID', data_files='Stock_price/full_history.zip')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Repo card metadata block was not found. Setting CardData to empty.
WARNING:huggingface_hub.repocard:Repo card metadata block was not found. Setting CardData to empty.

Generating train split: 0 examples [00:00, ? examples/s]

In [ ]:
import pandas as pd

okdokey = dataset['train'][0:1000]
okdokey = pd.DataFrame(dataset['train'])
okdokey

In [ ]:
okdokey

NameError: name 'okdokey' is not defined

In [ ]:
!unzip Stock_price/full_history.zip -d full_history

In [ ]:
import pandas as pd
news_data = pd.read_csv('All_external.csv')
market_data = pd.read_csv('All_market.csv')

In [ ]:
dataset

NameError: name 'dataset' is not defined

# Classifying news using GLiClass Instruct

Hugging Face: https://huggingface.co/knowledgator/gliclass-instruct-large-v1.0

In [1]:
!pip install -q gliclass

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.4/47.4 kB 2.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 76.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 24.8 MB/s eta 0:00:00

In [16]:
pipeline(['what is love?', 'big tech is so good!'], labels=['energy', 'tech'], threshold=0.02)

100%|██████████| 1/1 [00:00<00:00,  9.62it/s]

[[{'label': 'energy', 'score': 0.805618941783905},
  {'label': 'tech', 'score': 0.21098583936691284}],
 [{'label': 'energy', 'score': 0.09507032483816147}]]

In [2]:
from gliclass import GLiClassModel, ZeroShotClassificationPipeline
from transformers import AutoTokenizer

model = GLiClassModel.from_pretrained("knowledgator/gliclass-instruct-large-v1.0")
tokenizer = AutoTokenizer.from_pretrained("knowledgator/gliclass-instruct-large-v1.0")
pipeline = ZeroShotClassificationPipeline(model, tokenizer, classification_type='multi-label', device='cuda:0')

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.75G [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

spm.model:   0%|          | 0.00/2.46M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/92.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/970 [00:00<?, ?B/s]

In [6]:
text = "TTF prices up 2% this morning because of oil"
labels = ["energy", "finance", "tech", "health"]

# examples = [
#     {"text": "TTF prices are up by 5%.", "labels": ["energy"]},
#     {"text": "Boycots will affect the oil prices.", "labels": ["energy"]},
#     {"text": "CEO of Starbucks is retiering.", "labels": ["not energy"]},
# ]

results = pipeline(text, labels, threshold=0.02)[0]
print()
for r in results:
    print(r["label"], "=>", r["score"])

100%|██████████| 1/1 [00:00<00:00,  1.88it/s]

energy => 0.7042527794837952
finance => 0.7362023591995239
tech => 0.11519643664360046

In [7]:
import pandas as pd
data = pd.read_csv('nasdaq_exteral_data_Y.csv')
data = data.set_index('Unnamed: 0')
data.index.name = None
data = data[data.index.notna()]
data.head()

,Date,Article_title,Stock_symbol,Url,Publisher,Author,Article,Lsa_summary,Luhn_summary,Textrank_summary,Lexrank_summary
2463320.0,2023-12-15 00:00:00 UTC,Worsening Deflation Pushes Inverse China ETF H...,YANG,https://www.nasdaq.com/articles/worsening-defl...,NaN,NaN,Worsening deflation is putting the Direxion Da...,"With YINN down 25%, traders can take the other...","With YINN down 25%, traders can take the other...","With YINN down 25%, traders can take the other...","With YINN down 25%, traders can take the other..."
2463321.0,2023-12-14 00:00:00 UTC,Top Performing Leveraged/Inverse ETFs: 12/10/2023,YANG,https://www.nasdaq.com/articles/top-performing...,NaN,NaN,Top Performing Levered/Inverse ETFs Last Week\...,YANG – Direxion Daily FTSE China Bear 3X Share...,(GDXD ) MicroSectors Gold Miners -3X Inverse L...,(GDXD ) MicroSectors Gold Miners -3X Inverse L...,(GDXD ) MicroSectors Gold Miners -3X Inverse L...
2463322.0,2023-12-13 00:00:00 UTC,Best Inverse/Leveraged ETFs of Last Week,YANG,https://www.nasdaq.com/articles/best-inverse-l...,NaN,NaN,The S&P 500 hit a new high for the year last w...,Direxion Daily FTSE China Bear 3X Shares YANG ...,Click to get this free report United States Oi...,Click to get this free report United States Oi...,Click to get this free report United States Oi...
2463323.0,2023-12-05 00:00:00 UTC,Top Performing Leveraged/Inverse ETFs: 12/03/2023,YANG,https://www.nasdaq.com/articles/top-performing...,NaN,NaN,These were last week's top performing leverage...,(GDXU B-) MicroSectors Gold Miners 3X Leverage...,(GDXU B-) MicroSectors Gold Miners 3X Leverage...,(GDXU B-) MicroSectors Gold Miners 3X Leverage...,(GDXU B-) MicroSectors Gold Miners 3X Leverage...
2463324.0,2023-11-01 00:00:00 UTC,Get in Early on China’s Economic Recovery With...,YANG,https://www.nasdaq.com/articles/get-in-early-o...,NaN,NaN,The Chinese government is injecting a dose of ...,"Additionally, if investor sentiment remains be...","Additionally, if investor sentiment remains be...","Additionally, if investor sentiment remains be...","Additionally, if investor sentiment remains be..."

In [8]:
data_small = data.iloc[:1000]
data_small = data_small['Lsa_summary']
# data_small

In [23]:
data_small_list = data_small.to_list()

In [26]:
result_test = pipeline(data_small_list, labels, threshold=0.5)

100%|██████████| 125/125 [01:12<00:00,  1.73it/s]

In [9]:
classified_labels = []
classified_scores = []

for text_to_classify in data_small:
    results = pipeline(text_to_classify, labels, threshold=0.5)[0]
    # Extract labels and scores
    flag = any(result['label'] == 'energy' for result in results)
    if flag:
        classified_labels.append('energy')
    else:
        classified_labels.append('not energy')

# Add the classified data back to the data_small DataFrame
res = pd.DataFrame(data_small) # Ensure data_small is a DataFrame to add columns
res['classified_labels'] = classified_labels

res.head()

100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
100%|██████████| 1/1 [00:00<00:00,  1.71it/s]
100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
100%|██████████| 1/1 [00:00<00:00,  9.53it/s]
100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
100%|██████████| 1/1 [00:00<00:00, 10.80it/s]
100%|██████████| 1/1 [00:00<00:00, 11.29it/s]
100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
100%|██████████| 1/1 [00:00<00:00, 11.32it/s]
100%|██████████| 1/1 [00:00<00:00, 10.05it/s]
100%|██████████| 1/1 [00:00<00:00, 11.99it/s]
100%|██████████| 1/1 [00:00<00:00, 19.37it/s]
100%|██████████| 1/1 [00:00<00:00, 10.12it/s]
100%|██████████| 1/1 [00:00<00:00, 12.75it/s]
100%|██████████| 1/1 [00:00<00:00,  9.57it/s]
100%|██████████| 1/1 [00:00<00:00, 14.49it/s]
100%|██████████| 1/1 [00:00<00:00, 14.64it/s]
100%|██████████| 1/1 [00:00<00:00, 12.71it/s]
100%|██████████| 1/1 [00:00<00:00, 19.04it/s]
100%|██████████| 1/1 [00:00<00:00,  9.76it/s]
100%|██████████| 1/1 [00:00<00:00, 11.67it/s]
100%|██████████| 1/1 [00:00<00:00,  9.99it/s]
100%|██████████| 1/1 [00:00<00:00, 15.52it/s]
100%|██████████| 1/1 [00:00<00:00, 18.65it/s]
100%|██████████| 1/1 [00:00<00:00, 10.31it/s]
100%|██████████| 1/1 [00:00<00:00, 13.05it/s]
100%|██████████| 1/1 [00:00<00:00, 19.33it/s]
100%|██████████| 1/1 [00:00<00:00, 16.12it/s]
100%|██████████| 1/1 [00:00<00:00, 18.92it/s]
100%|██████████| 1/1 [00:00<00:00, 10.17it/s]
100%|██████████| 1/1 [00:00<00:00, 16.43it/s]
100%|██████████| 1/1 [00:00<00:00, 18.81it/s]
100%|██████████| 1/1 [00:00<00:00, 10.50it/s]
100%|██████████| 1/1 [00:00<00:00, 15.09it/s]
100%|██████████| 1/1 [00:00<00:00, 13.76it/s]
100%|██████████| 1/1 [00:00<00:00, 18.98it/s]
100%|██████████| 1/1 [00:00<00:00,  9.80it/s]
100%|██████████| 1/1 [00:00<00:00,  8.37it/s]
100%|██████████| 1/1 [00:00<00:00, 13.15it/s]
100%|██████████| 1/1 [00:00<00:00, 10.01it/s]
100%|██████████| 1/1 [00:00<00:00, 11.26it/s]
100%|██████████| 1/1 [00:00<00:00, 18.80it/s]
100%|██████████| 1/1 [00:00<00:00, 15.77it/s]
100%|██████████| 1/1 [00:00<00:00, 10.87it/s]
100%|██████████| 1/1 [00:00<00:00, 10.09it/s]
100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
100%|██████████| 1/1 [00:00<00:00, 17.06it/s]
100%|██████████| 1/1 [00:00<00:00, 16.33it/s]
100%|██████████| 1/1 [00:00<00:00, 18.73it/s]
100%|██████████| 1/1 [00:00<00:00, 16.49it/s]
100%|██████████| 1/1 [00:00<00:00, 15.51it/s]
100%|██████████| 1/1 [00:00<00:00, 15.67it/s]
100%|██████████| 1/1 [00:00<00:00, 12.51it/s]
100%|██████████| 1/1 [00:00<00:00, 15.82it/s]
100%|██████████| 1/1 [00:00<00:00, 14.68it/s]
100%|██████████| 1/1 [00:00<00:00, 14.63it/s]
100%|██████████| 1/1 [00:00<00:00, 14.61it/s]
100%|██████████| 1/1 [00:00<00:00, 14.86it/s]
100%|██████████| 1/1 [00:00<00:00, 15.54it/s]
100%|██████████| 1/1 [00:00<00:00, 16.17it/s]
100%|██████████| 1/1 [00:00<00:00, 14.99it/s]
100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
100%|██████████| 1/1 [00:00<00:00, 14.62it/s]
100%|██████████| 1/1 [00:00<00:00, 14.76it/s]
100%|██████████| 1/1 [00:00<00:00, 14.89it/s]
100%|██████████| 1/1 [00:00<00:00, 15.25it/s]
100%|██████████| 1/1 [00:00<00:00, 14.44it/s]
100%|██████████| 1/1 [00:00<00:00, 12.81it/s]
100%|██████████| 1/1 [00:00<00:00, 14.30it/s]
100%|██████████| 1/1 [00:00<00:00, 14.91it/s]
100%|██████████| 1/1 [00:00<00:00, 14.39it/s]
100%|██████████| 1/1 [00:00<00:00, 16.97it/s]
100%|██████████| 1/1 [00:00<00:00, 14.67it/s]
100%|██████████| 1/1 [00:00<00:00, 14.83it/s]
100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
100%|██████████| 1/1 [00:00<00:00, 16.23it/s]
100%|██████████| 1/1 [00:00<00:00, 15.34it/s]
100%|██████████| 1/1 [00:00<00:00, 15.62it/s]
100%|██████████| 1/1 [00:00<00:00, 15.04it/s]
100%|██████████| 1/1 [00:00<00:00, 19.82it/s]
100%|██████████| 1/1 [00:00<00:00, 19.40it/s]
100%|██████████| 1/1 [00:00<00:00, 15.54it/s]
100%|██████████| 1/1 [00:00<00:00, 19.49it/s]
100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
100%|██████████| 1/1 [00:00<00:00, 18.74it/s]
100%|██████████| 1/1 [00:00<00:00, 17.88it/s]
100%|██████████| 1/1 [00:00<00:00, 15.27it/s]
100%|██████████| 1/1 [00:00<00:00, 19.86it/s]
100%|██████████| 1/1 [00:00<00:00, 20.14it/s]
100%|██████████| 1/1 [00:00<00:00, 19.80it/s]
100%|██████████| 1/1 [00:00<00:00, 14.88it/s]
100%|██████████| 1/1 [00:00<00:00, 14.93it/s]
100%|██████████| 1/1 [00:00<00:00, 18.32it/s]
100%|██████████| 1/1 [00:00<00:00, 17.85it/s]
100%|██████████| 1/1 [00:00<00:00, 18.16it/s]
100%|██████████| 1/1 [00:00<00:00, 15.97it/s]
100%|██████████| 1/1 [00:00<00:00, 15.17it/s]
100%|██████████| 1/1 [00:00<00:00,  2.35it/s]
100%|██████████| 1/1 [00:00<00:00,  2.34it/s]
100%|██████████| 1/1 [00:00<00:00, 16.03it/s]
100%|██████████| 1/1 [00:00<00:00, 15.17it/s]
100%|██████████| 1/1 [00:00<00:00,  2.32it/s]
100%|██████████| 1/1 [00:00<00:00, 19.61it/s]
100%|██████████| 1/1 [00:00<00:00, 15.97it/s]
100%|██████████| 1/1 [00:00<00:00, 15.56it/s]
100%|██████████| 1/1 [00:00<00:00, 17.88it/s]
100%|██████████| 1/1 [00:00<00:00, 15.96it/s]
100%|██████████| 1/1 [00:00<00:00, 18.55it/s]
100%|██████████| 1/1 [00:00<00:00, 14.87it/s]
100%|██████████| 1/1 [00:00<00:00, 19.56it/s]
100%|██████████| 1/1 [00:00<00:00, 19.21it/s]
100%|██████████| 1/1 [00:00<00:00, 19.71it/s]
100%|██████████| 1/1 [00:00<00:00, 16.68it/s]
100%|██████████| 1/1 [00:00<00:00, 18.81it/s]
100%|██████████| 1/1 [00:00<00:00, 20.16it/s]
100%|██████████| 1/1 [00:00<00:00, 16.50it/s]
100%|██████████| 1/1 [00:00<00:00, 16.11it/s]
100%|██████████| 1/1 [00:00<00:00, 18.89it/s]
100%|██████████| 1/1 [00:00<00:00, 15.39it/s]
100%|██████████| 1/1 [00:00<00:00, 16.94it/s]
100%|██████████| 1/1 [00:00<00:00, 14.75it/s]
100%|██████████| 1/1 [00:00<00:00, 15.54it/s]
100%|██████████| 1/1 [00:00<00:00, 18.33it/s]
100%|██████████| 1/1 [00:00<00:00, 18.01it/s]
100%|██████████| 1/1 [00:00<00:00, 19.59it/s]
100%|██████████| 1/1 [00:00<00:00, 19.45it/s]
100%|██████████| 1/1 [00:00<00:00, 16.05it/s]
100%|██████████| 1/1 [00:00<00:00, 11.34it/s]
100%|██████████| 1/1 [00:00<00:00, 15.03it/s]
100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
100%|██████████| 1/1 [00:00<00:00, 14.93it/s]
100%|██████████| 1/1 [00:00<00:00, 15.25it/s]
100%|██████████| 1/1 [00:00<00:00, 17.67it/s]
100%|██████████| 1/1 [00:00<00:00, 14.75it/s]
100%|██████████| 1/1 [00:00<00:00, 14.68it/s]
100%|██████████| 1/1 [00:00<00:00, 15.12it/s]
100%|██████████| 1/1 [00:00<00:00, 11.71it/s]
100%|██████████| 1/1 [00:00<00:00, 12.09it/s]
100%|██████████| 1/1 [00:00<00:00, 14.17it/s]
100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
100%|██████████| 1/1 [00:00<00:00, 14.57it/s]
100%|██████████| 1/1 [00:00<00:00, 13.33it/s]
100%|██████████| 1/1 [00:00<00:00, 14.02it/s]
100%|██████████| 1/1 [00:00<00:00, 12.00it/s]
100%|██████████| 1/1 [00:00<00:00, 15.02it/s]
100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
100%|██████████| 1/1 [00:00<00:00, 14.44it/s]
100%|██████████| 1/1 [00:00<00:00, 11.21it/s]
100%|██████████| 1/1 [00:00<00:00, 14.53it/s]
100%|██████████| 1/1 [00:00<00:00, 14.85it/s]
100%|██████████| 1/1 [00:00<00:00, 14.81it/s]
100%|██████████| 1/1 [00:00<00:00, 15.01it/s]
100%|██████████| 1/1 [00:00<00:00, 16.11it/s]
100%|██████████| 1/1 [00:00<00:00, 16.38it/s]
100%|██████████| 1/1 [00:00<00:00, 15.81it/s]
100%|██████████| 1/1 [00:00<00:00, 16.24it/s]
100%|██████████| 1/1 [00:00<00:00, 16.10it/s]
100%|██████████| 1/1 [00:00<00:00, 12.37it/s]
100%|██████████| 1/1 [00:00<00:00, 11.82it/s]
100%|██████████| 1/1 [00:00<00:00, 12.86it/s]
100%|██████████| 1/1 [00:00<00:00, 15.59it/s]
100%|██████████| 1/1 [00:00<00:00, 12.97it/s]
100%|██████████| 1/1 [00:00<00:00, 10.65it/s]
100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
100%|██████████| 1/1 [00:00<00:00, 12.24it/s]
100%|██████████| 1/1 [00:00<00:00, 11.48it/s]
100%|██████████| 1/1 [00:00<00:00, 11.42it/s]
100%|██████████| 1/1 [00:00<00:00, 11.59it/s]
100%|██████████| 1/1 [00:00<00:00, 17.19it/s]
100%|██████████| 1/1 [00:00<00:00, 17.93it/s]
100%|██████████| 1/1 [00:00<00:00, 19.04it/s]
100%|██████████| 1/1 [00:00<00:00, 18.33it/s]
100%|██████████| 1/1 [00:00<00:00, 17.88it/s]
100%|██████████| 1/1 [00:00<00:00, 14.78it/s]
100%|██████████| 1/1 [00:00<00:00, 15.55it/s]
100%|██████████| 1/1 [00:00<00:00, 19.10it/s]
100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
100%|██████████| 1/1 [00:00<00:00, 18.67it/s]
100%|██████████| 1/1 [00:00<00:00, 18.76it/s]
100%|██████████| 1/1 [00:00<00:00, 19.72it/s]
100%|██████████| 1/1 [00:00<00:00, 18.95it/s]
100%|██████████| 1/1 [00:00<00:00, 19.73it/s]
100%|██████████| 1/1 [00:00<00:00, 19.04it/s]
100%|██████████| 1/1 [00:00<00:00, 15.06it/s]
100%|██████████| 1/1 [00:00<00:00, 19.49it/s]
100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
100%|██████████| 1/1 [00:00<00:00, 20.00it/s]
100%|██████████| 1/1 [00:00<00:00, 17.54it/s]
100%|██████████| 1/1 [00:00<00:00, 15.41it/s]
100%|██████████| 1/1 [00:00<00:00, 18.20it/s]
100%|██████████| 1/1 [00:00<00:00, 19.16it/s]
100%|██████████| 1/1 [00:00<00:00, 14.81it/s]
100%|██████████| 1/1 [00:00<00:00, 14.74it/s]
100%|██████████| 1/1 [00:00<00:00, 19.26it/s]
100%|██████████| 1/1 [00:00<00:00, 14.45it/s]
100%|██████████| 1/1 [00:00<00:00, 18.47it/s]
100%|██████████| 1/1 [00:00<00:00, 19.41it/s]
100%|██████████| 1/1 [00:00<00:00, 15.16it/s]
100%|██████████| 1/1 [00:00<00:00, 14.39it/s]
100%|██████████| 1/1 [00:00<00:00, 17.76it/s]
100%|██████████| 1/1 [00:00<00:00, 14.85it/s]
100%|██████████| 1/1 [00:00<00:00, 14.18it/s]
100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
100%|██████████| 1/1 [00:00<00:00, 14.68it/s]
100%|██████████| 1/1 [00:00<00:00, 18.71it/s]
100%|██████████| 1/1 [00:00<00:00, 18.75it/s]
100%|██████████| 1/1 [00:00<00:00, 18.87it/s]
100%|██████████| 1/1 [00:00<00:00, 15.06it/s]
100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
100%|██████████| 1/1 [00:00<00:00, 18.82it/s]
100%|██████████| 1/1 [00:00<00:00, 15.49it/s]
100%|██████████| 1/1 [00:00<00:00, 19.06it/s]
100%|██████████| 1/1 [00:00<00:00, 19.56it/s]
100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
100%|██████████| 1/1 [00:00<00:00, 14.96it/s]
100%|██████████| 1/1 [00:00<00:00, 19.02it/s]
100%|██████████| 1/1 [00:00<00:00, 18.20it/s]
100%|██████████| 1/1 [00:00<00:00, 18.74it/s]
100%|██████████| 1/1 [00:00<00:00, 14.94it/s]
100%|██████████| 1/1 [00:00<00:00, 18.98it/s]
100%|██████████| 1/1 [00:00<00:00, 19.39it/s]
100%|██████████| 1/1 [00:00<00:00, 18.54it/s]
100%|██████████| 1/1 [00:00<00:00, 14.56it/s]
100%|██████████| 1/1 [00:00<00:00, 14.74it/s]
100%|██████████| 1/1 [00:00<00:00, 14.20it/s]
100%|██████████| 1/1 [00:00<00:00, 19.59it/s]
100%|██████████| 1/1 [00:00<00:00, 14.39it/s]
100%|██████████| 1/1 [00:00<00:00, 13.71it/s]
100%|██████████| 1/1 [00:00<00:00, 19.49it/s]
100%|██████████| 1/1 [00:00<00:00, 20.03it/s]
100%|██████████| 1/1 [00:00<00:00, 19.27it/s]
100%|██████████| 1/1 [00:00<00:00, 13.75it/s]
100%|██████████| 1/1 [00:00<00:00, 18.61it/s]
100%|██████████| 1/1 [00:00<00:00, 16.37it/s]
100%|██████████| 1/1 [00:00<00:00, 15.40it/s]
100%|██████████| 1/1 [00:00<00:00, 16.44it/s]
100%|██████████| 1/1 [00:00<00:00, 16.19it/s]
100%|██████████| 1/1 [00:00<00:00, 18.31it/s]
100%|██████████| 1/1 [00:00<00:00, 19.19it/s]
100%|██████████| 1/1 [00:00<00:00, 15.12it/s]
100%|██████████| 1/1 [00:00<00:00, 19.98it/s]
100%|██████████| 1/1 [00:00<00:00, 15.45it/s]
100%|██████████| 1/1 [00:00<00:00, 17.18it/s]
100%|██████████| 1/1 [00:00<00:00, 14.59it/s]
100%|██████████| 1/1 [00:00<00:00, 18.65it/s]
100%|██████████| 1/1 [00:00<00:00, 19.39it/s]
100%|██████████| 1/1 [00:00<00:00, 19.52it/s]
100%|██████████| 1/1 [00:00<00:00, 14.79it/s]
100%|██████████| 1/1 [00:00<00:00, 14.30it/s]
100%|██████████| 1/1 [00:00<00:00, 14.49it/s]
100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
100%|██████████| 1/1 [00:00<00:00, 18.59it/s]
100%|██████████| 1/1 [00:00<00:00, 14.56it/s]
100%|██████████| 1/1 [00:00<00:00, 14.61it/s]
100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
100%|██████████| 1/1 [00:00<00:00, 19.44it/s]
100%|██████████| 1/1 [00:00<00:00, 18.69it/s]
100%|██████████| 1/1 [00:00<00:00, 14.32it/s]
100%|██████████| 1/1 [00:00<00:00, 18.26it/s]
100%|██████████| 1/1 [00:00<00:00, 15.39it/s]
100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
100%|██████████| 1/1 [00:00<00:00, 19.82it/s]
100%|██████████| 1/1 [00:00<00:00, 14.83it/s]
100%|██████████| 1/1 [00:00<00:00, 15.33it/s]
100%|██████████| 1/1 [00:00<00:00, 17.27it/s]
100%|██████████| 1/1 [00:00<00:00, 18.36it/s]
100%|██████████| 1/1 [00:00<00:00, 18.15it/s]
100%|██████████| 1/1 [00:00<00:00, 18.91it/s]
100%|██████████| 1/1 [00:00<00:00, 18.28it/s]
100%|██████████| 1/1 [00:00<00:00, 15.02it/s]
100%|██████████| 1/1 [00:00<00:00, 18.26it/s]
100%|██████████| 1/1 [00:00<00:00, 15.61it/s]
100%|██████████| 1/1 [00:00<00:00, 18.64it/s]
100%|██████████| 1/1 [00:00<00:00, 18.09it/s]
100%|██████████| 1/1 [00:00<00:00, 18.35it/s]
100%|██████████| 1/1 [00:00<00:00, 15.18it/s]
100%|██████████| 1/1 [00:00<00:00, 14.78it/s]
100%|██████████| 1/1 [00:00<00:00, 14.52it/s]
100%|██████████| 1/1 [00:00<00:00, 18.87it/s]
100%|██████████| 1/1 [00:00<00:00, 18.30it/s]
100%|██████████| 1/1 [00:00<00:00, 18.64it/s]
100%|██████████| 1/1 [00:00<00:00, 15.07it/s]
100%|██████████| 1/1 [00:00<00:00, 17.33it/s]
100%|██████████| 1/1 [00:00<00:00, 16.20it/s]
100%|██████████| 1/1 [00:00<00:00, 13.91it/s]
100%|██████████| 1/1 [00:00<00:00, 18.21it/s]
100%|██████████| 1/1 [00:00<00:00, 18.60it/s]
100%|██████████| 1/1 [00:00<00:00, 19.41it/s]
100%|██████████| 1/1 [00:00<00:00, 15.29it/s]
100%|██████████| 1/1 [00:00<00:00, 13.31it/s]
100%|██████████| 1/1 [00:00<00:00, 18.90it/s]
100%|██████████| 1/1 [00:00<00:00, 14.97it/s]
100%|██████████| 1/1 [00:00<00:00, 18.03it/s]
100%|██████████| 1/1 [00:00<00:00, 18.48it/s]
100%|██████████| 1/1 [00:00<00:00, 18.94it/s]
100%|██████████| 1/1 [00:00<00:00, 18.62it/s]
100%|██████████| 1/1 [00:00<00:00, 14.37it/s]
100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
100%|██████████| 1/1 [00:00<00:00, 19.13it/s]
100%|██████████| 1/1 [00:00<00:00, 14.65it/s]
100%|██████████| 1/1 [00:00<00:00, 17.96it/s]
100%|██████████| 1/1 [00:00<00:00, 14.51it/s]
100%|██████████| 1/1 [00:00<00:00, 15.18it/s]
100%|██████████| 1/1 [00:00<00:00, 18.20it/s]
100%|██████████| 1/1 [00:00<00:00, 18.92it/s]
100%|██████████| 1/1 [00:00<00:00, 18.35it/s]
100%|██████████| 1/1 [00:00<00:00, 18.63it/s]
100%|██████████| 1/1 [00:00<00:00, 19.80it/s]
100%|██████████| 1/1 [00:00<00:00, 15.73it/s]
100%|██████████| 1/1 [00:00<00:00, 15.84it/s]
100%|██████████| 1/1 [00:00<00:00, 18.33it/s]
100%|██████████| 1/1 [00:00<00:00, 19.00it/s]
100%|██████████| 1/1 [00:00<00:00, 19.85it/s]
100%|██████████| 1/1 [00:00<00:00, 19.13it/s]
100%|██████████| 1/1 [00:00<00:00, 17.67it/s]
100%|██████████| 1/1 [00:00<00:00, 19.49it/s]
100%|██████████| 1/1 [00:00<00:00, 12.65it/s]
100%|██████████| 1/1 [00:00<00:00, 14.73it/s]
100%|██████████| 1/1 [00:00<00:00, 18.63it/s]
100%|██████████| 1/1 [00:00<00:00, 18.60it/s]
100%|██████████| 1/1 [00:00<00:00, 18.46it/s]
100%|██████████| 1/1 [00:00<00:00, 14.88it/s]
100%|██████████| 1/1 [00:00<00:00, 18.49it/s]
100%|██████████| 1/1 [00:00<00:00, 14.72it/s]
100%|██████████| 1/1 [00:00<00:00, 17.62it/s]
100%|██████████| 1/1 [00:00<00:00, 16.39it/s]
100%|██████████| 1/1 [00:00<00:00, 19.00it/s]
100%|██████████| 1/1 [00:00<00:00, 11.47it/s]
100%|██████████| 1/1 [00:00<00:00, 13.21it/s]
100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
100%|██████████| 1/1 [00:00<00:00, 13.97it/s]
100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
100%|██████████| 1/1 [00:00<00:00, 13.50it/s]
100%|██████████| 1/1 [00:00<00:00, 13.62it/s]
100%|██████████| 1/1 [00:00<00:00, 14.63it/s]
100%|██████████| 1/1 [00:00<00:00, 15.15it/s]
100%|██████████| 1/1 [00:00<00:00, 15.84it/s]
100%|██████████| 1/1 [00:00<00:00, 15.35it/s]
100%|██████████| 1/1 [00:00<00:00, 14.75it/s]
100%|██████████| 1/1 [00:00<00:00, 12.83it/s]
100%|██████████| 1/1 [00:00<00:00, 14.72it/s]
100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
100%|██████████| 1/1 [00:00<00:00, 14.82it/s]
100%|██████████| 1/1 [00:00<00:00, 15.47it/s]
100%|██████████| 1/1 [00:00<00:00, 14.52it/s]
100%|██████████| 1/1 [00:00<00:00, 14.23it/s]
100%|██████████| 1/1 [00:00<00:00, 15.60it/s]
100%|██████████| 1/1 [00:00<00:00, 13.03it/s]
100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
100%|██████████| 1/1 [00:00<00:00, 13.29it/s]
100%|██████████| 1/1 [00:00<00:00, 12.95it/s]
100%|██████████| 1/1 [00:00<00:00, 12.15it/s]
100%|██████████| 1/1 [00:00<00:00, 13.85it/s]
100%|██████████| 1/1 [00:00<00:00, 13.44it/s]
100%|██████████| 1/1 [00:00<00:00, 11.20it/s]
100%|██████████| 1/1 [00:00<00:00, 11.88it/s]
100%|██████████| 1/1 [00:00<00:00, 13.34it/s]
100%|██████████| 1/1 [00:00<00:00, 11.28it/s]
100%|██████████| 1/1 [00:00<00:00, 11.14it/s]
100%|██████████| 1/1 [00:00<00:00, 11.87it/s]
100%|██████████| 1/1 [00:00<00:00, 14.25it/s]
100%|██████████| 1/1 [00:00<00:00, 18.92it/s]
100%|██████████| 1/1 [00:00<00:00, 16.68it/s]
100%|██████████| 1/1 [00:00<00:00, 18.48it/s]
100%|██████████| 1/1 [00:00<00:00, 15.15it/s]
100%|██████████| 1/1 [00:00<00:00, 18.00it/s]
100%|██████████| 1/1 [00:00<00:00, 14.89it/s]
100%|██████████| 1/1 [00:00<00:00, 13.78it/s]
100%|██████████| 1/1 [00:00<00:00, 14.50it/s]
100%|██████████| 1/1 [00:00<00:00, 17.67it/s]
100%|██████████| 1/1 [00:00<00:00, 18.56it/s]
100%|██████████| 1/1 [00:00<00:00, 17.99it/s]
100%|██████████| 1/1 [00:00<00:00, 15.48it/s]
100%|██████████| 1/1 [00:00<00:00, 13.60it/s]
100%|██████████| 1/1 [00:00<00:00, 17.47it/s]
100%|██████████| 1/1 [00:00<00:00, 14.22it/s]
100%|██████████| 1/1 [00:00<00:00, 17.80it/s]
100%|██████████| 1/1 [00:00<00:00,  3.30it/s]
100%|██████████| 1/1 [00:00<00:00, 14.07it/s]
100%|██████████| 1/1 [00:00<00:00, 14.04it/s]
100%|██████████| 1/1 [00:00<00:00, 14.48it/s]
100%|██████████| 1/1 [00:00<00:00, 18.23it/s]
100%|██████████| 1/1 [00:00<00:00, 14.91it/s]
100%|██████████| 1/1 [00:00<00:00, 14.13it/s]
100%|██████████| 1/1 [00:00<00:00,  2.21it/s]
100%|██████████| 1/1 [00:00<00:00, 14.47it/s]
100%|██████████| 1/1 [00:00<00:00, 13.70it/s]
100%|██████████| 1/1 [00:00<00:00,  2.19it/s]
100%|██████████| 1/1 [00:00<00:00,  2.24it/s]
100%|██████████| 1/1 [00:00<00:00,  2.20it/s]
100%|██████████| 1/1 [00:00<00:00,  2.22it/s]
100%|██████████| 1/1 [00:00<00:00, 13.95it/s]
100%|██████████| 1/1 [00:00<00:00, 18.54it/s]
100%|██████████| 1/1 [00:00<00:00,  6.10it/s]
100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
100%|██████████| 1/1 [00:00<00:00, 15.61it/s]
100%|██████████| 1/1 [00:00<00:00, 17.17it/s]
100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
100%|██████████| 1/1 [00:00<00:00, 14.06it/s]
100%|██████████| 1/1 [00:00<00:00, 14.06it/s]
100%|██████████| 1/1 [00:00<00:00,  7.78it/s]
100%|██████████| 1/1 [00:00<00:00,  5.75it/s]
100%|██████████| 1/1 [00:00<00:00,  4.67it/s]
100%|██████████| 1/1 [00:00<00:00,  4.86it/s]
100%|██████████| 1/1 [00:00<00:00,  4.45it/s]
100%|██████████| 1/1 [00:00<00:00,  4.70it/s]
100%|██████████| 1/1 [00:00<00:00,  4.75it/s]
100%|██████████| 1/1 [00:00<00:00,  4.80it/s]
100%|██████████| 1/1 [00:00<00:00,  3.18it/s]
100%|██████████| 1/1 [00:00<00:00,  2.04it/s]
100%|██████████| 1/1 [00:00<00:00,  5.90it/s]
100%|██████████| 1/1 [00:00<00:00,  4.95it/s]
100%|██████████| 1/1 [00:00<00:00,  6.29it/s]
100%|██████████| 1/1 [00:00<00:00,  6.07it/s]
100%|██████████| 1/1 [00:00<00:00,  5.78it/s]
100%|██████████| 1/1 [00:00<00:00,  9.48it/s]
100%|██████████| 1/1 [00:00<00:00, 14.62it/s]
100%|██████████| 1/1 [00:00<00:00, 18.72it/s]
100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
100%|██████████| 1/1 [00:00<00:00, 13.48it/s]
100%|██████████| 1/1 [00:00<00:00, 13.92it/s]
100%|██████████| 1/1 [00:00<00:00, 17.95it/s]
100%|██████████| 1/1 [00:00<00:00, 14.83it/s]
100%|██████████| 1/1 [00:00<00:00, 18.18it/s]
100%|██████████| 1/1 [00:00<00:00, 11.38it/s]
100%|██████████| 1/1 [00:00<00:00, 17.46it/s]
100%|██████████| 1/1 [00:00<00:00, 14.76it/s]
100%|██████████| 1/1 [00:00<00:00, 13.88it/s]
100%|██████████| 1/1 [00:00<00:00, 19.01it/s]
100%|██████████| 1/1 [00:00<00:00, 15.26it/s]
100%|██████████| 1/1 [00:00<00:00, 18.81it/s]
100%|██████████| 1/1 [00:00<00:00, 15.30it/s]
100%|██████████| 1/1 [00:00<00:00, 16.05it/s]

                                                 Lsa_summary classified_labels
2463320.0  With YINN down 25%, traders can take the other...        not energy
2463321.0  YANG – Direxion Daily FTSE China Bear 3X Share...        not energy
2463322.0  Direxion Daily FTSE China Bear 3X Shares YANG ...            energy
2463323.0  (GDXU B-) MicroSectors Gold Miners 3X Leverage...        not energy
2463324.0  Additionally, if investor sentiment remains be...        not energy

In [11]:
len(res[res['classified_labels'] == 'energy'])

34

In [125]:
res[res['classified_labels'] == 'energy'].index

Index([2466322.0, 2466331.0, 2466332.0, 2466338.0, 2466346.0, 2466356.0,
       2466357.0, 2466358.0, 2466364.0, 2466368.0, 2466369.0, 2466370.0,
       2466371.0, 2466372.0, 2466373.0, 2466378.0, 2466379.0, 2466387.0,
       2466403.0, 2466407.0, 2466414.0, 2466417.0],
      dtype='float64')

In [123]:
for article in res[res['classified_labels'] == 'energy']['Lsa_summary']:
    print(article)
    print('\n')

By Stephanie Kelly, Jarrett Renshaw and Leah Douglas NEW YORK, Dec 14 (Reuters) - The Biden administration is expected this week to recognize a soon-to-be-updated methodology favored by the ethanol industry in guidance to companies looking to claim tax credits for sustainable aviation fuel (SAF), three people familiar with the matter told Reuters. As it stands, that model would enable ethanol-based SAF to qualify for tax credits under the Inflation Reduction Act, President Joe Biden's signature climate law. One of environmental groups' central concerns about the use of the GREET model - that it would underestimate the emissions generated by tilling land for crops - appears to be unresolved, said Nikita Pavlenko, fuels team lead at the International Council on Clean Transportation.


Front-month gas futures NGc1 for January delivery on the New York Mercantile Exchange were up 1.2 cents, or 0.5%, to $2.35 per million British thermal units (mmBtu) at 12:45 p.m. EST (1745 GMT). "We will repeat a view that mild temperature trends will be contributing to a significant increase in the storage surplus back to as much as 330-340 bcf by month's end," analysts at energy advisory Ritterbusch and Associates said in a note. Gas was trading around $11 per mmBtu at the Dutch Title Transfer Facility (TTF) benchmark in Europe TRNLTTFMc1 and $15 at the Japan Korea Marker (JKM) in Asia JKMc1.


Shares of ChargePoint Holdings (NYSE: CHPT), the world's largest independent charging network for electric vehicles (EVs), were rallying today in response to the Federal Reserve's interest rate announcement yesterday, trending with other beaten-down stocks that stand to benefit from lower interest rates and the jolt they are expected to give to the economy. The Fed's forecast for lower interest rates shouldn't do much to affect ChargePoint's business directly, but it is breathing new life into the stock. There's no shortage of challenges facing Wilmer as he aims to deliver positive adjusted earnings before interest, taxes, depreciation, and amortization (EBITDA) by the fourth quarter of next year, but stronger EV demand would help.


Finally, many factories are being built to facilitate the energy transition and EV revolution, while a high number of data centers are under construction to enable the proliferation of AI. As a result, the company has benefited significantly from the huge increases in the amount of money spent on building factories in North America. The Rich Use This Income Secret (NOT Dividends) Far More Than Regular Investors The post 3 Heavily Undervalued Industrial Stocks to Buy in December appeared first on InvestorPlace.


Analysts and investors alike will be keeping a close eye on the performance of Hologic in its upcoming earnings disclosure. At the same time, our most recent consensus estimate is projecting a revenue of $978.36 million, reflecting an 8.92% fall from the equivalent quarter last year. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


The company's annualized cash flow growth rate has been 12% over the past 3-5 years versus the industry average of 6.5%. Empirical research shows that there is a strong correlation between trends in earnings estimate revisions and near-term stock price movements. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


Analysts and investors alike will be keeping a close eye on the performance of Meta Platforms in its upcoming earnings disclosure. As a result, upbeat changes in estimates indicate analysts' favorable outlook on the company's business health and profitability. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


Its 3-year average annual operating income growth rate is more than 100%, showing the firm has the financial chops to cut costs amid energy market volatility. Ultimately, though KRP’s recent performance seems poor on paper, this oil and gas stock is set to rebound from renewed energy market enthusiasm. This week, Buffet added to his position and bought an additional $590 million worth of stock after the firm announced an imminent acquisition of a private oil and gas company.


For the quarter ended November 2023, Lennar (LEN) reported revenue of $10.97 billion, up 7.8% over the same period last year. While investors closely watch year-over-year changes in headline numbers -- revenue and earnings -- and how they compare to Wall Street expectations to determine their next course of action, some key metrics always provide a better insight into a company's underlying performance. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


Meanwhile, the latest consensus estimate predicts the revenue to be $4.05 billion, indicating a 6.42% increase compared to the same quarter of the previous year. To exploit this, we've formed the Zacks Rank, a quantitative model that includes these estimate changes and presents a viable rating system. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


Meanwhile, the latest consensus estimate predicts the revenue to be $9.69 billion, indicating a 11.89% increase compared to the same quarter of the previous year. To exploit this, we've formed the Zacks Rank, a quantitative model that includes these estimate changes and presents a viable rating system. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


At the same time, our most recent consensus estimate is projecting a revenue of $357.55 million, reflecting a 20.2% rise from the equivalent quarter last year. To take advantage of this, we've established the Zacks Rank, an exclusive model that considers these estimated changes and delivers an operational rating system. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


In the meantime, our current consensus estimate forecasts the revenue to be $303.66 million, indicating a 14.88% growth compared to the corresponding quarter of the prior year. To benefit from this, we have developed the Zacks Rank, a proprietary model which takes these estimate changes into account and provides an actionable rating system. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


In the latest market close, Hershey (HSY) reached $186.21, with a -1.37% movement compared to the previous day. To exploit this, we've formed the Zacks Rank, a quantitative model that includes these estimate changes and presents a viable rating system. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


This is thanks to a nearly +11% run-up in the past month on the small-cap index — 2.6% just today — as higher interest rate levels previously expected through much of next year are on the wane, thanks to a newly dovish Fed, as of yesterday. For now, though, market participants and the Fed are celebrating a well-earned respite following 2022 pressures that kept big gains at bay and carried a looming dark cloud of recession ahead of it at all times. Click here>> The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


For the annual period, the Zacks Consensus Estimates anticipate earnings of $4.14 per share and a revenue of $39.61 billion, signifying shifts of +16.95% and +10.09%, respectively, from the last year. To benefit from this, we have developed the Zacks Rank, a proprietary model which takes these estimate changes into account and provides an actionable rating system. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


Alongside, our most recent consensus estimate is anticipating revenue of $230.22 million, indicating a 57.11% upward movement from the same quarter last year. To exploit this, we've formed the Zacks Rank, a quantitative model that includes these estimate changes and presents a viable rating system. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


After reaching an important support level, Zuora (ZUO) could be a good stock pick from a technical perspective. Investors may want to watch ZUO for more gains in the near future given the company's key technical level and positive earnings estimate revisions. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


Here is one stock with buy rank and strong income characteristics for investors to consider today, December 144: Western Midstream Partners, LP WES: This midstream energy company has witnessed the Zacks Consensus Estimate for its current year earnings increasing 4.4% the last 60 days. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains. Download the brand-new FREE report revealing 5 EV battery stocks set to soar.


Empirical research shows a strong correlation between near-term stock movements and trends in earnings estimate revisions. While the magnitude and direction of estimate revisions could change following the company's just-released earnings report, the current status translates into a Zacks Rank #2 (Buy) for the stock. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.


Adds detail from paragraph 2 STOCKHOLM, Dec 14 (Reuters) - Norway's Equinor .OL> said on Thursday it has agreed to buy Shell's SHEL.L stake in the Linnorm gas discovery in the Norwegian Sea, raising its ownership to 50%. Equinor said the Linnorm find is the largest undeveloped gas discovery on the Norwegian Continental Shelf and is estimated to contain around 25-30 billion cubic meters (bcm) of recoverable gas resources. "This does not impact our ambition to maintain a material upstream position," Shell Norway Managing Director Marianne Olsnes said in the joint statement.


This company that connects borrowers and lenders online is expected to post quarterly earnings of $0.03 per share in its upcoming report, which represents a year-over-year change of -84.2%. Columbia Financial's consensus EPS estimate for the upcoming report has remained unchanged over the past month at $0.07. The New Gold Rush: How Lithium Batteries Will Make Millionaires As the electric vehicle revolution expands, investors have a chance to target huge gains.

In [ ]:
any(result == 'energy' for result in results)